
{% set version = "2.3.14" %}
{% set sha256 = "7fec17147ecb183e32a9d48b1d7380d9939a2e30551cab57e027f10313c454d3" %}

{% set build = 0 %}
{% if blas_impl == 'openblas' %}
{% set build = build + 100 %}
{% endif %}

{% set blas_prefix = blas_impl %}

package:
  name: toast
  version: {{ version }}

source:
  #url: https://github.com/hpc4cmb/toast/archive/{{ version }}.tar.gz
  url: https://github.com/hpc4cmb/toast/archive/forgefix.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True  # [py<37]
  skip: True  # [win]
  number: {{ build }}
  string: "{{ blas_prefix }}_py{{ py }}h{{ PKG_HASH }}_{{ build }}"
  run_exports:
    - toast * {{ blas_prefix }}_*

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - llvm-openmp >=4.0.1  # [osx]
  host:
    - llvm-openmp >=4.0.1  # [osx]
    - python
    - fftw  # [blas_impl == 'openblas']
    - openblas * openmp_*  # [blas_impl == 'openblas']
    - mkl-devel  # [blas_impl == 'mkl']
    - liblapack
    - suitesparse
    - libaatm
  run:
    - llvm-openmp >=4.0.1  # [osx]
    - python
    - {{ pin_compatible("fftw") }}  # [blas_impl == 'openblas']
    - openblas * openmp_*  # [blas_impl == 'openblas']
    - {{ pin_compatible("mkl") }}  # [blas_impl == 'mkl']
    - {{ pin_compatible("liblapack") }}
    - {{ pin_compatible("suitesparse") }}
    - {{ pin_compatible("libaatm") }}
    - numpy
    - scipy
    - astropy
    - healpy
    - h5py
    - ephem

test:
  files:
    - run_test.sh
  commands:
    - ./run_test.sh

about:
  home: https://github.com/hpc4cmb/toast
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Time Ordered Astrophysics Scalable Tools'
  description: |
    TOAST is a software framework for simulating and processing timestream data
    collected by microwave telescopes.
  dev_url: https://github.com/hpc4cmb/toast

extra:
  recipe-maintainers:
    - tskisner
